name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    strategy:
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-15-arm64-Readme.md
        os: [macos-13, macos-14, macos-15]
    name: Build
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .deps
          key: ${{ matrix.os }}-${{ runner.arch }}-${{ hashFiles('script/install-dep.sh', 'Gemfile', '.bundle/config') }}
      - run: brew install bash fish xcbeautify
      - run: ./script/install-dep.sh --all
      - run: ./build-debug.sh
      - run: ./run-tests.sh
        # "-" means "Sign to run locally". There is no aerospace-codesign-certificate in GH Actions
        # build-release.sh takes too much time to complete in macos-13.
        # Running build-release.sh only in macos-15, cuts the build time twice in GH Actions.
      - name: ./build-release.sh on macos-15
        run: |
          sw_vers -productVersion
          if sw_vers -productVersion | grep -q "^15"; then
            ./build-release.sh --codesign-identity -
            ./install-from-sources.sh --dont-rebuild
          fi
  static-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install SwiftLint
      run: brew install swiftlint

    - name: Run SwiftLint
      run: swiftlint lint --strict

  malware-scan:
    name: Malware Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install ClamAV
      run: sudo apt-get install -y clamav

    - name: Update ClamAV Database
      run: sudo freshclam

    - name: Scan Repository
      run: clamscan -r .
